### ISSUE TITLE
Tensor parallel using triton flash attn return wrong output on Max1100 & hang on card 1 on B60

### ISSUE THREAD

**Issue by cyita** [intel/intel-xpu-backend-for-triton#4730]
### Describe the bug

I try to run Tensor parallel (TP=2) with torch distributed package and Triton Flash Attention kernel similar to https://github.com/intel/intel-xpu-backend-for-triton/blob/main/benchmarks/triton_kernels_benchmark/flash_attention_benchmark.py.

#### On b60 * 2
The Triton kernel hangs on card 1 (card 0 works fine). This issue occurs not only with the complex flash attention operation but also with a simple position ID calculation.

#### On Max1100 * 2
The Triton flash attention kernel does not hang, but the output is incorrect.

Does Triton support the tensor parallel scenario on B60 or Max1100? How can I resolve these issues?

### Environment details

Triton: pytorch-triton-xpu                       3.3.0

#### ENV 1
GPU: B60 * 2
```
intel_extension_for_pytorch              2.7.10+xpu
pytorch-triton-xpu                       3.3.0
torch                                    2.7.0+xpu
torchao                                  0.9.0
torchaudio                               2.7.0+xpu
torchvision                              0.22.0+xpu
```

#### ENV2
GPU: Max1100 * 2
```
intel_extension_for_pytorch              2.7.10+xpu
pytorch-triton-xpu                       3.3.0
torch                                    2.7.0+xpu
torchao                                  0.9.0
torchaudio                               2.7.0+xpu
torchvision                              0.22.0+xpu
```

**Comment by anmyachev** [comment]
Should be atleast related to https://github.com/intel/intel-xpu-backend-for-triton/issues/4733#issuecomment-3083301741

**Comment by cyita** [comment]
> Should be atleast related to [#4733 (comment)](https://github.com/intel/intel-xpu-backend-for-triton/issues/4733#issuecomment-3083301741)

Yes, https://github.com/intel/intel-xpu-backend-for-triton/issues/4733#issuecomment-3083301741 solved my problem. Thanks a lot!
