### ISSUE TITLE
Triton vector add failed on multi-card env with error UR_RESULT_ERROR_DEVICE_LOST on xpu:1

### ISSUE THREAD

**Issue by cyita** [intel/intel-xpu-backend-for-triton#4733]
### Bug description
I have two B60 GPUs, and I want to launch a Triton kernel on both cards 0 and 1. However, I found that it always fails on card 1. This is why I cannot use export ONEAPI_DEVICE_SELECTOR=level_zero:xxx to select the XPU.

When I try to run a simple add kernel on XPU:1, it either raises `UR_RESULT_ERROR_DEVICE_LOST` or produces an incorrect result.

How can I resolve this issue and successfully run the Triton kernel on both cards?

#### case 1: rank 0, correct result
```
import torch
import intel_extension_for_pytorch
import triton
import triton.language as tl
```
```
rank = 0
torch.get_device_module("xpu").set_device(rank)
tensor = test_add_kernel(rank)
print(f'Rank {rank} before all_reduce: {tensor}')
```

```
x: tensor([2., 2., 2.,  ..., 2., 2., 2.], device='xpu:0')

y: tensor([5., 5., 5.,  ..., 5., 5., 5.], device='xpu:0')

Rank 0 before all_reduce: tensor([7., 7., 7.,  ..., 7., 7., 7.], device='xpu:0')
```

#### case 2: rank 1, w/ import intel_extension_for_pytorch, UR_RESULT_ERROR_DEVICE_LOST
```
import torch
import intel_extension_for_pytorch
import triton
import triton.language as tl
```
```
rank = 1
torch.get_device_module("xpu").set_device(rank)
tensor = test_add_kernel(rank)
print(f'Rank {rank} before all_reduce: {tensor}')
```
<img width="1351" height="461" alt="Image" src="https://github.com/user-attachments/assets/2dd2531e-dcef-48e3-8293-412c82266ff1" />

#### case 3: rank 1, w/o import intel_extension_for_pytorch, incorrect output
```
import torch
import triton
import triton.language as tl
```
```
rank = 1
torch.get_device_module("xpu").set_device(rank)
tensor = test_add_kernel(rank)
print(f'Rank {rank} before all_reduce: {tensor}')
```

```
x: tensor([2., 2., 2.,  ..., 2., 2., 2.], device='xpu:1')

y: tensor([5., 5., 5.,  ..., 5., 5., 5.], device='xpu:1')

Rank 1 before all_reduce: tensor([5., 5., 5.,  ..., 1., 1., 1.], device='xpu:1')
```

#### case 4: rank 1, w/o import intel_extension_for_pytorch, w/o torch set_device, incorrect output
```
import torch
import triton
import triton.language as tl
```

```
rank = 1
tensor = test_add_kernel(rank)
print(f'Rank {rank} before all_reduce: {tensor}')
```

```
x: tensor([2., 2., 2.,  ..., 2., 2., 2.], device='xpu:1')

y: tensor([5., 5., 5.,  ..., 5., 5., 5.], device='xpu:1')

Rank 1 before all_reduce: tensor([2.4307e-29, 1.9714e+30, 8.1871e-34,  ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00], device='xpu:1')
```

### Sample Code:
Based on the vector add example: https://github.com/intel/intel-xpu-backend-for-triton/blob/main/python/tutorials/01-vector-add.py
```
import torch
import triton
import triton.language as tl

@triton.jit
def add_kernel(x_ptr,  # *Pointer* to first input vector.
               y_ptr,  # *Pointer* to second input vector.
               output_ptr,  # *Pointer* to output vector.
               n_elements,  # Size of the vector.
               BLOCK_SIZE: tl.constexpr,  # Number of elements each program should process.
               # NOTE: `constexpr` so it can be used as a shape value.
               ):
    # There are multiple 'programs' processing different data. We identify which program
    # we are here:
    pid = tl.program_id(axis=0)  # We use a 1D launch grid so axis is 0.
    # This program will process inputs that are offset from the initial data.
    # For instance, if you had a vector of length 256 and block_size of 64, the programs
    # would each access the elements [0:64, 64:128, 128:192, 192:256].
    # Note that offsets is a list of pointers:
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    # Create a mask to guard memory operations against out-of-bounds accesses.
    mask = offsets < n_elements
    # Load x and y from DRAM, masking out any extra elements in case the input is not a
    # multiple of the block size.
    x = tl.load(x_ptr + offsets, mask=mask)
    y = tl.load(y_ptr + offsets, mask=mask)
    output = x + y
    # Write x + y back to DRAM.
    tl.store(output_ptr + offsets, output, mask=mask)


def add(x: torch.Tensor, y: torch.Tensor):
    # We need to preallocate the output.
    output = torch.empty_like(x)
    # assert x.device == DEVICE and y.device == DEVICE and output.device == DEVICE
    n_elements = output.numel()
    # The SPMD launch grid denotes the number of kernel instances that run in parallel.
    # It is analogous to CUDA launch grids. It can be either Tuple[int], or Callable(metaparameters) -> Tuple[int].
    # In this case, we use a 1D grid where the size is the number of blocks:
    grid = lambda meta: (triton.cdiv(n_elements, meta['BLOCK_SIZE']), )
    # NOTE:
    #  - Each torch.tensor object is implicitly converted into a pointer to its first element.
    #  - `triton.jit`'ed functions can be indexed with a launch grid to obtain a callable GPU kernel.
    #  - Don't forget to pass meta-parameters as keywords arguments.
    add_kernel[grid](x, y, output, n_elements, BLOCK_SIZE=1024)
    # We return a handle to z but, since `torch.cuda.synchronize()` hasn't been called, the kernel is still
    # running asynchronously at this point.
    return output


def test_add_kernel(rank):
    size = 98432
    x = torch.ones(size, device=f"xpu:{rank}") * 2
    y = torch.ones(size, device=f"xpu:{rank}") * 5
    print(f"x: {x}\n")
    print(f"y: {y}\n")
    output_triton = add(x, y)
    return output_triton

if __name__ == "__main__":

    rank = 0
    torch.get_device_module("xpu").set_device(rank)
    tensor = test_add_kernel(rank)
    print(f'Rank {rank} before all_reduce: {tensor}')
```

### Environment details

```
intel_extension_for_pytorch              2.7.10+xpu
pytorch-triton-xpu                       3.3.0
torch                                    2.7.0+xpu
```

```
b60 * 2 + Intel(R) Xeon(R) w5-3435X
```

**Comment by anmyachev** [comment]
> pytorch-triton-xpu                       3.3.0

Hi @cyita!

I believe it's fixed by https://github.com/intel/intel-xpu-backend-for-triton/commit/ca4e8573e3a168ac9b4854a1a55dd6beddb8fd0b but this commit is not included into 3.3.0 release.

Do you have a chance to use more recent Triton?

For a quick test, you can patch your current package, as it's only a few lines of python code (though I don't recommend doing this unless you've tried it before).

**Comment by cyita** [comment]
Hi @anmyachev, this solved the `set_device` case! 
I found that the nightly build supports torch==2.9.0? How can I find a wheel with this commit and support Torch 2.7.0?

**Comment by anmyachev** [comment]
> Hi [@anmyachev](https://github.com/anmyachev), this solved the `set_device` case!

Good!


> I found that the nightly build supports torch==2.9.0?

yes

> How can I find a wheel with this commit and support Torch 2.7.0?

There are most likely none, since when pytorch 2.7 was built, this commit did not exist yet.

**Comment by anmyachev** [comment]
Feel free to reopen if needed
