### ISSUE TITLE
[flash-linear-attention] Bug Issues with Intel XPU Backend for Triton on B580 GPU

### ISSUE THREAD

**Issue by zhiyuan1i** [intel/intel-xpu-backend-for-triton#4838]
### Describe the bug

Hello Intel team,

I am currently working on the [flash-linear-attention](https://github.com/fla-org/flash-linear-attention) project, which aims to provide efficient implementations of state-of-the-art linear attention models. Previously, I used the Intel A770 GPU, and I was quite impressed with the stability of its Triton support. However, I recently upgraded to the B580 GPU and encountered some issues that I believe are worth investigating.

### Background

The Intel A770's Triton support was generally stable, but there were some hardware limitations, such as the inability to allocate more than 4GB of GPU memory for a single tensor and a small SRAM size. While these limitations did pose challenges for certain algorithms, they also motivated us to develop solutions that are more suitable for non-cloud service GPUs.
Status for B580, it's reported that B580 has more shared memory than A100, which is powerful and useful for our development.
Therefore I upgraded to a B580 GPU.
```
 triton.runtime.driver.active.utils.get_device_properties(0)
{'max_shared_mem': 131072, 'multiprocessor_count': 20, 'sm_clock_rate': 2900, 'mem_clock_rate': 0, 'mem_bus_width': 64, 'max_work_group_size': 1024, 'sub_group_sizes': (16, 32)}
```
### Issues Encountered

During my testing with the B580 GPU(triton 3.4.0), I encountered several bugs, most of which are `RuntimeError: PassManager::run failed`. There are also a few instances of `RuntimeError: Native API failed. Native API returns: 39 (UR_RESULT_ERROR_OUT_OF_DEVICE_MEMORY)` , `RuntimeError: UR error` and some numercial issue.

Also, some check reports nan in float16(we use float16 instead of bfloat16 in tests to make sure our implementation is correct.) We first set seeds and then create tensors on CPU, then to.(device) and compute, those kernels seems correct on Nvidia and AMD, or maybe A770(I cant remember)

### Reproduction Steps

To reproduce these issues, you can follow these steps:

1. Install the latest nightly build of PyTorch with XPU support:
   ```
   pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/xpu
   ```

2. Clone the flash-linear-attention repository:
   ```
   git clone https://github.com/fla-org/flash-linear-attention.git
   ```

3. Check out the specific branch (tmp-remove-all-intel-skip) that I used for testing:
   ```
   cd flash-linear-attention
   git checkout tmp-remove-all-intel-skip
   ```

4. Install the project and its dependencies:
   ```
   pip install .
   pip install pytest
   ```

5. Run the tests:
   ```
   pytest tests/ops
   ```

### Expected Behavior

I expect the tests to run smoothly without encountering the aforementioned RuntimeError issues. However, the current behavior indicates that there might be some compatibility problems between the B580 GPU and the Triton backend.

### Request for Assistance

I kindly ask the Intel team to look into this issue and provide any necessary guidance or fixes. Your support would be greatly appreciated, as it would help us ensure better compatibility and performance for non-NVIDIA GPUs in our project.

Thank you for your attention and assistance.

Best regards

<details>
<summary>Some outputs</summary>

```
tests/ops/test_attn.py::test_parallel[B1-T63-H1-HQ1-D64-scale1.0] SKIPPED (Skipping test because flash-attn is n...) [  0%]
tests/ops/test_attn.py::test_parallel[B3-T111-H2-HQ2-D100-scale1.0] SKIPPED (Skipping test because flash-attn is...) [  0%]
tests/ops/test_attn.py::test_parallel[B3-T1024-H2-HQ8-D60-scale0.1] SKIPPED (Skipping test because flash-attn is...) [  0%]
tests/ops/test_attn.py::test_parallel[B3-T1024-H2-HQ8-D128-scale0.1] SKIPPED (Skipping test because flash-attn i...) [  0%]
tests/ops/test_attn.py::test_parallel[B4-T2048-H2-HQ8-D64-scale0.1] SKIPPED (Skipping test because flash-attn is...) [  1%]
tests/ops/test_attn.py::test_parallel_varlen[H2-HQ2-D64-cu_seqlens[0, 15]] SKIPPED (Skipping test because flash-...) [  1%]
tests/ops/test_attn.py::test_parallel_varlen[H2-HQ8-D64-cu_seqlens[0, 256, 500, 1000]] SKIPPED (Skipping test be...) [  1%]
tests/ops/test_attn.py::test_parallel_varlen[H2-HQ2-D100-cu_seqlens[0, 15, 100, 300, 1200, 2000]] SKIPPED (Skipp...) [  1%]
tests/ops/test_based.py::test_based[B1-T63-H1-D60-torch.float16] FAILED                                              [  2%]
tests/ops/test_based.py::test_based[B3-T111-H2-D64-torch.float16] FAILED                                             [  2%]
tests/ops/test_based.py::test_based[B3-T1024-H4-D100-torch.float16] FAILED                                           [  2%]
tests/ops/test_based.py::test_based[B3-T1024-H8-D128-torch.float16] FAILED                                           [  2%]
tests/ops/test_based.py::test_based[B4-T2048-H8-D256-torch.float16] FAILED                                           [  2%]
tests/ops/test_comba.py::test_chunk[B2-T1000-H3-D60-scale1-gate_logit_normalizer1-mask_p0-use_qk_l2norm_in_kernelFalse-torch.float16] 
------------------------------------------------------ live log call -------------------------------------------------------
INFO     fla.utils:utils.py:80                o diff: nan ratio: nan
FAILED                                                                                                               [  5%]
tests/ops/test_comba.py::test_chunk[B2-T1024-H4-D100-scale1-gate_logit_normalizer0.1-mask_p0-use_qk_l2norm_in_kernelFalse-torch.float16] 
------------------------------------------------------ live log call -------------------------------------------------------
INFO     fla.utils:utils.py:80                o diff: nan ratio: nan
FAILED                                                                                                               [  6%]                                                                                                              [  9%]
tests/ops/test_delta.py::test_chunk_varlen[H3-D60-cu_seqlens[0, 111, 500]-torch.float16] 
------------------------------------------------------ live log call -------------------------------------------------------
INFO     fla.utils:utils.py:80                o diff: nan ratio: nan
FAILED                                                                                                               [  9%]
tests/ops/test_delta.py::test_chunk_varlen[H4-D100-cu_seqlens[0, 15, 100, 300, 1200, 1599, 1800, 2000]-torch.float16] 
------------------------------------------------------ live log call -------------------------------------------------------
INFO     fla.utils:utils.py:80                o diff: 10.453125 ratio: 1.637726
FAILED                                                                                                               [ 10%]
INFO     fla.utils:utils.py:80                o diff: nan ratio: nan
FAILED                                                                                                               [ 10%]                                                                                                        [ 11%]
tests/ops/test_delta_product.py::test_chunk[B2-T2048-H8-D128-scale1-num_householder3-l2normFalse-torch.float16] Segmentation fault
tests/ops/test_delta.py::test_chunk[B2-T100-H4-D60-scale0.1-False] 
------------------------------------------------------ live log call -------------------------------------------------------
INFO     fla.utils:utils.py:80                o diff: 0.667969 ratio: 1.517581
```

### Environment details

GPU B580
pytorch-triton-xpu     3.4.0+gitae324eea
torch                  2.9.0.dev20250802+xpu
torchaudio             2.8.0.dev20250802+xpu
torchvision            0.24.0.dev20250802+xpu

**Comment by etiotto** [comment]
@anmyachev could you please try to reproduce the problem reported and please open specific Triton issues if you discover problems in the compiler. Thanks.

**Comment by anmyachev** [comment]
I can reproduce some problems. One of them is in #4866. @etiotto could you take a look?

**Comment by etiotto** [comment]
> I can reproduce some problems. One of them is in [#4866](https://github.com/intel/intel-xpu-backend-for-triton/issues/4866). [@etiotto](https://github.com/etiotto) could you take a look?

#4866 is fixed @anmyachev

**Comment by zhiyuan1i** [comment]
Thank you for fix my issue. :)

After upgrading to pytorch_triton_xpu-3.4.0+gitd0e80f39, There still some fails.

Here is an example  with a ZE_RESULT_ERROR_MODULE_BUILD_FAILURE coming from the Intel Triton backend.


pytest tests/ops/test_delta_product.py::test_chunk[B2-T2048-H8-D128-scale1-num_householder3-l2normFalse-torch.float16] -v



```
 fla/ops/delta_rule/chunk.py:152: in forward
    o, A, final_state = chunk_delta_rule_fwd(
fla/ops/delta_rule/chunk.py:43: in chunk_delta_rule_fwd
    o = chunk_fwd_o(
fla/ops/common/chunk_o.py:501: in chunk_fwd_o
    chunk_fwd_kernel_o[grid](
/home/lzy/miniconda3/envs/fla/lib/python3.12/site-packages/triton/runtime/jit.py:393: in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/lzy/miniconda3/envs/fla/lib/python3.12/site-packages/triton/runtime/autotuner.py:452: in run
    return self.fn.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/lzy/miniconda3/envs/fla/lib/python3.12/site-packages/triton/runtime/autotuner.py:238: in run
    benchmark()
/home/lzy/miniconda3/envs/fla/lib/python3.12/site-packages/triton/runtime/autotuner.py:227: in benchmark
    timings = {config: self._bench(*args, config=config, **kwargs) for config in pruned_configs}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/lzy/miniconda3/envs/fla/lib/python3.12/site-packages/triton/runtime/autotuner.py:162: in _bench
    return self.do_bench(kernel_call, quantiles=(0.5, 0.2, 0.8))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/lzy/miniconda3/envs/fla/lib/python3.12/site-packages/triton/testing.py:149: in do_bench
    fn()
/home/lzy/miniconda3/envs/fla/lib/python3.12/site-packages/triton/runtime/autotuner.py:148: in kernel_call
    self.fn.run(
/home/lzy/miniconda3/envs/fla/lib/python3.12/site-packages/triton/runtime/jit.py:623: in run
    kernel.run(grid_0, grid_1, grid_2, stream, kernel.function, kernel.packed_metadata, launch_metadata,
    ^^^^^^^^^^
/home/lzy/miniconda3/envs/fla/lib/python3.12/site-packages/triton/compiler/compiler.py:474: in __getattribute__
    self._init_handles()
/home/lzy/miniconda3/envs/fla/lib/python3.12/site-packages/triton/compiler/compiler.py:462: in _init_handles
    self.module, self.function, self.n_regs, self.n_spills, self.n_max_threads = driver.active.utils.load_binary(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <triton.backends.intel.driver.SpirvUtils object at 0x760175b27a10>
args = ('chunk_fwd_kernel_o', b'\x03\x02#\x07\x00\x04\x01\x00\x0e\x00\x06\x00\\\x07\x00\x00\x00\x00\x00\x00\x11\x00\x02\x00\x...\x00\x00\xdc\x06\x00\x00\xdd\x06\x00\x00\xde\x06\x00\x00\xdf\x06\x00\x00\xfd\x00\x01\x008\x00\x01\x00', 0, '', True, 0)

    def load_binary(self, *args):
        # if we don't use parameter passing in this way,
        # we will need to rewrite the line in the general part of the code:
        # driver.active.utils.load_binary(self.name, self.kernel, self.metadata.shared, self.metadata.build_flags, device) ->
        # driver.active.utils.load_binary((self.name, self.kernel, self.metadata.shared, self.metadata.build_flags, device))
>       return self.shared_library.load_binary(args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
E       RuntimeError: ZE_RESULT_ERROR_MODULE_BUILD_FAILURE

/home/lzy/miniconda3/envs/fla/lib/python3.12/site-packages/triton/backends/intel/driver.py:213: RuntimeError
---------------------------------------------------- Captured stderr call -----------------------------------------------------
L0 build module failed. Log: IGC: Internal Compiler Error: Segmentation violation

Error during Intel loadBinary: ZE_RESULT_ERROR_MODULE_BUILD_FAILURE
=================================================== short test summary info ===================================================
FAILED tests/ops/test_delta_product.py::test_chunk[B2-T2048-H8-D128-scale1-num_householder3-l2normFalse-torch.float16] - RuntimeError: ZE_RESULT_ERROR_MODULE_BUILD_FAILURE
```

**Comment by anmyachev** [comment]
Hi @zhiyuan1i! I tried this particular test on our main branch (https://github.com/intel/intel-xpu-backend-for-triton/commit/ce08f575191c5ba47b8fd22f37fdcaa69327efa0) and it works. Could you try our latest changes?

```bash
collected 1 item

tests/ops/test_delta_product.py::test_chunk[B2-T2048-H8-D128-scale1-num_householder3-l2normFalse-torch.float16]
----------------------------------------------------------------------- live log call -----------------------------------------------------------------------
INFO     fla.utils:utils.py:80                o diff: 0.001953 ratio: 0.000366
INFO     fla.utils:utils.py:80               ht diff: 0.000000 ratio: 0.000000
INFO     fla.utils:utils.py:80               dq diff: 0.000000 ratio: 0.000000
INFO     fla.utils:utils.py:80               dk diff: 0.000000 ratio: 0.000000
INFO     fla.utils:utils.py:80               dv diff: 0.000000 ratio: 0.000000
INFO     fla.utils:utils.py:80               db diff: 0.000000 ratio: 0.000000
INFO     fla.utils:utils.py:80              dh0 diff: 0.000000 ratio: 0.000000
PASSED                                                                                                                                                [100%]

=============================================================== 1 passed in 223.44s (0:03:43) ===============================================================
```

**Comment by zhiyuan1i** [comment]
@anmyachev Thank you for your work. I understand how challenging it is to support a wide range of use cases on consumer-grade GPUs.

QWEN-NEXT is already using the flash-linear-attention repository in public. To make it easier for them to integrate into Transformers, vLLM duplicated the kernels, so we released fla-core. After testing, a few sample cases still fail, but the good news is that none of those failing kernels are used by Qwen.


Running `pytest tests/ops` directly can trigger a failure that kills the entire test process and causes all subsequent cases to abort.


And there are some numercial issues. For example:
pytest tests/ops/test_forgetting_attn.py

tests/ops/test_forgetting_attn.py::test_parallel[B3-T111-H2-HQ2-D100-scale1.0] 
-------------------------------------------------------------------------------------------------- live log call ---------------------------------------------------------------------------------------------------
INFO     fla.utils:utils.py:80                o diff: 0.001038 ratio: 0.000199
INFO     fla.utils:utils.py:80               dq diff: 88.187500 ratio: 2.678133
FAILED

**Comment by anmyachev** [comment]
> tests/ops/test_forgetting_attn.py::test_parallel[B3-T111-H2-HQ2-D100-scale1.0]

I can reproduce it on main.

> Running pytest tests/ops directly can trigger a failure that kills the entire test process and causes all subsequent cases to abort.

Yeh, I'm sorry that this is so, we will do our best to fix this. Could you please tell us which tests are more important? With this we will be able to help you more productively.

**Comment by zhiyuan1i** [comment]
@anmyachev  Thank you for your reply!
For QWEN3-NEXT, related tests are: `tests/modules/test_conv.py`, `tests/modules/test_layernorm.py`, `tests/modules/test_layernorm_gated.py` and `tests/ops/test_gated_delta.py`.

I’ve verified that all four tests run perfectly in my environment, except for
```
FAILED tests/modules/test_layernorm.py::test_groupnorm[True-1-512-512-2] – RuntimeError: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
FAILED tests/modules/test_layernorm.py::test_groupnorm[True-4-2048-512-2] – RuntimeError: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
FAILED tests/modules/test_layernorm.py::test_groupnorm[False-1-512-512-2] – RuntimeError: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
FAILED tests/modules/test_layernorm.py::test_groupnorm[False-4-2048-512-2] – RuntimeError: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
```
Since these shapes are synthetic, I’m concerned the real Qwen model may still hit issues; we’ll have to wait until the weights are open-sourced to know for sure.
The remaining operator tests are less urgent—they’re still in the academic-research stage and haven’t been deployed at scale.
We also have an unpublished algorithm that I haven’t tested on Intel yet; if any compatibility problems appear, I’ll update this issue after the tech report is released.

**Comment by anmyachev** [comment]
As a workaround you could disable `num_warps=2` case at least for XPU from
https://github.com/fla-org/flash-linear-attention/blob/f7d95fa04fcb2df07390b1bf8b7d6b96ffb7a16a/fla/modules/layernorm.py#L329

After that `tests/modules/test_layernorm.py::test_groupnorm[True-1-512-512-2]` starts to work (**UPD:** all `test_groupnorm` cases work).

A bit context: the error occurs during autotuning. Probably we should properly raise `OutOfResources` in this case which autotuner can handle.
