### ISSUE TITLE
[BMG] FlexAttention (batch_size=16) Causal Mask fwd kernel benchmark failure

### ISSUE THREAD

**Issue by dev-tomek** [intel/intel-xpu-backend-for-triton#5603]
Followup #5481.
`RuntimeError: Native API failed. Native API returns: 20 (UR_RESULT_ERROR_DEVICE_LOST)` error visible on  FlexAttention (batch_size=16) Causal Mask fwd kernel benchmark on BMG runner `triton-bmg-499320`. Applying the same fix as in #5481 does not resolve the issue.

Failing job:
https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/19854824092/job/56890032648

**Comment by dev-tomek** [comment]
Checked on PVC, and the memory reservation for the following test case `[16, 128, 128, 1024, 1024, 192, 128, fwd, torch]` is equal to  `~31510.0 MB` -> way more than BMG capacity and that is when the error is thrown.

**Next steps:** Need to figure out why its not visible on other BMG runners in the CI

**Comment by dev-tomek** [comment]
Issue resolved. This configuration is normally skipped in CI on BMG based on the runner label. In this case the runner label was changed to target and diagnose #5481, thus this test case ran when its supposed to be skipped. 
Once the runner label is changed back, therell be no error.
