### ISSUE TITLE
RuntimeError: level_zero backend failed with error: 45 (UR_RESULT_ERROR_INVALID_ARGUMENT)

### ISSUE THREAD

**Issue by anmyachev** [intel/intel-xpu-backend-for-triton#5815]
`test_print` doesn't work on A770: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/20987091669/job/60324593350#step:16:29452

Seems related to https://github.com/pytorch/pytorch/issues/170166

**Comment by anmyachev** [comment]
Fixed after PyTorch pin update. Good CI run: https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/21794944043/job/62881474284
