### ISSUE TITLE
[Bug] Error during Intel loadBinary: ZE_RESULT_ERROR_INVALID_KERNEL_NAME

### ISSUE THREAD

**Issue by montaguelhz** [intel/intel-xpu-backend-for-triton#6027]
### Describe the bug

I encountered a error when compiling `_w8a8_triton_block_scaled_mm` in [vllm](https://github.com/vllm-project/vllm/blob/808dd87b305426c809a21b2a6a4fb3ea607bca3f/vllm/model_executor/layers/quantization/utils/fp8_utils.py#L1173) to support offline fp8 quantization in intel GPU. 
```
(EngineCore_DP0 pid=8084) WARNING 02-02 07:13:14 [_logger.py:68] Using default W8A8 Block FP8 kernel config. Performance might be sub-optimal! Config file not found at /llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/utils/configs/N=4096,K=1024,device_name=Intel(R)_Graphics_[0xe211],dtype=fp8_w8a8,block_shape=[128,128].json
Error during Intel loadBinary: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
......
(EngineCore_DP0 pid=8084)   File "/llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/ipex_quant.py", line 411, in apply
(EngineCore_DP0 pid=8084)     return self.w8a8_block_fp8_linear.apply(
(EngineCore_DP0 pid=8084)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/utils/fp8_utils.py", line 257, in apply
(EngineCore_DP0 pid=8084)     output = self.w8a8_blockscale_op(
(EngineCore_DP0 pid=8084)              ^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/utils/fp8_utils.py", line 366, in _run_triton
(EngineCore_DP0 pid=8084)     return torch.ops.vllm.w8a8_triton_block_scaled_mm_func(
(EngineCore_DP0 pid=8084)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/torch/_ops.py", line 1255, in __call__
(EngineCore_DP0 pid=8084)     return self._op(*args, **kwargs)
(EngineCore_DP0 pid=8084)            ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/utils/fp8_utils.py", line 80, in _w8a8_triton_block_scaled_mm_func
(EngineCore_DP0 pid=8084)     return w8a8_triton_block_scaled_mm(
(EngineCore_DP0 pid=8084)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/llm/llm-scaler-vllm-xpu/vllm/model_executor/layers/quantization/utils/fp8_utils.py", line 846, in w8a8_triton_block_scaled_mm
(EngineCore_DP0 pid=8084)     _w8a8_triton_block_scaled_mm[grid](
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/triton/runtime/jit.py", line 393, in <lambda>
(EngineCore_DP0 pid=8084)     return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
(EngineCore_DP0 pid=8084)                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/triton/runtime/jit.py", line 623, in run
(EngineCore_DP0 pid=8084)     kernel.run(grid_0, grid_1, grid_2, stream, kernel.function, kernel.packed_metadata, launch_metadata,
(EngineCore_DP0 pid=8084)     ^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/triton/compiler/compiler.py", line 474, in __getattribute__
(EngineCore_DP0 pid=8084)     self._init_handles()
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/triton/compiler/compiler.py", line 462, in _init_handles
(EngineCore_DP0 pid=8084)     self.module, self.function, self.n_regs, self.n_spills, self.n_max_threads = driver.active.utils.load_binary(
(EngineCore_DP0 pid=8084)                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084)   File "/usr/local/lib/python3.12/dist-packages/triton/backends/intel/driver.py", line 213, in load_binary
(EngineCore_DP0 pid=8084)     return self.shared_library.load_binary(args)
(EngineCore_DP0 pid=8084)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8084) RuntimeError: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
```

### Environment details

The triton version is 3.5.1 and GPU is Intel B60.

**Comment by montaguelhz** [comment]
I try to change `num_warps` to 8 like #5394  and it works.

**Comment by quinnlp** [comment]
Hi @montaguelhz, it's possible that this is fixed by https://github.com/intel/intel-xpu-backend-for-triton/pull/6028 and https://github.com/pytorch/pytorch/pull/169167.

Could you please share the steps to a reproduce the issue? Thanks.

**Comment by montaguelhz** [comment]
> Hi [@montaguelhz](https://github.com/montaguelhz), it's possible that this is fixed by [#6028](https://github.com/intel/intel-xpu-backend-for-triton/pull/6028) and [pytorch/pytorch#169167](https://github.com/pytorch/pytorch/pull/169167).
> 
> Could you please share the steps to a reproduce the issue? Thanks.

I try to upgrade `trition` version to `3.6.0`, and the error log is
```
Module doesn't contain any kernels. Please attempt to tune the 'num_warps' parameter.
Error during Intel loadBinary: ZE_RESULT_ERROR_INVALID_KERNEL_NAME
```
I could understand the specific reason, but this configuration works fine under NVIDIA GPU.

**Comment by quinnlp** [comment]
PR that introduced IntelGPUError: https://github.com/intel/intel-xpu-backend-for-triton/pull/5628

**Comment by quinnlp** [comment]
I thought that this would be fixed by catching the `IntelGPUError`, but it seems that it is failing to compile the **default config**. So, its not a config that we can discard and we need to understand why we cannot compile it.

@Egor-Krivov, now that I realize that only the default config is being compiled I can directly run the triton kernel source with the config. I will not need to build/instal vllm from source like I mentioned before.

**Comment by montaguelhz** [comment]
> I thought that this would be fixed by catching the `IntelGPUError`, but it seems that it is failing to compile the **default config**. So, its not a config that we can discard and we need to understand why we cannot compile it.
> 
> [@Egor-Krivov](https://github.com/Egor-Krivov), now that I realize that only the default config is being compiled I can directly run the triton kernel source with the config. I will not need to build/instal vllm from source like I mentioned before.

The following are some parameter details, hopefully they will be helpful.  Additionally, I found that the end-to-end performance is severely degraded, only 1.3 tokens/s in Qwen-0.8B-FP8. I replaced the triton kernel with the C++ implementation, and the result is 0.7 tokens/s.
```
print(A.shape,B.shape,C.shape,As.shape,Bs.shape,M,N,K,block_n,block_k)
# torch.Size([8096, 3072]) torch.Size([1024, 3072]) torch.Size([8096, 1024]) torch.Size([8096, 24]) torch.Size([8, 24]) 8096 1024 3072 128 128
print(A.device,B.device,As.device,Bs.device)
# xpu:0 xpu:0 xpu:0 xpu:0
```

**Comment by quinnlp** [comment]
@montaguelhz 

It seems that the compilation failure is fixed on recent wheels. I was able to compile and run `_w8a8_triton_block_scaled_mm` using this [wheel](https://github.com/intel/intel-xpu-backend-for-triton/actions/runs/21844726471) and this script:
```python
import torch
import triton
import triton.language as tl

@triton.jit
def _w8a8_triton_block_scaled_mm(
    # Pointers to inputs and output
    A,
    B,
    C,
    As,
    Bs,
    # Shape for matmul
    M,
    N,
    K,
    # Block size for block-wise quantization
    group_n,
    group_k,
    # Stride for inputs and output
    stride_am,
    stride_ak,
    stride_bk,
    stride_bn,
    stride_cm,
    stride_cn,
    stride_As_m,
    stride_As_k,
    stride_Bs_k,
    stride_Bs_n,
    # Meta-parameters
    BLOCK_SIZE_M: tl.constexpr,
    BLOCK_SIZE_N: tl.constexpr,
    BLOCK_SIZE_K: tl.constexpr,
    GROUP_SIZE_M: tl.constexpr,
):
    """Triton-accelerated function used to perform linear operations (dot
    product) on input tensors `A` and `B` with block-wise quantization, and
    store the result in output tensor `C`.
    """

    pid = tl.program_id(axis=0)
    num_pid_m = tl.cdiv(M, BLOCK_SIZE_M)
    num_pid_n = tl.cdiv(N, BLOCK_SIZE_N)
    num_pid_in_group = GROUP_SIZE_M * num_pid_n
    group_id = pid // num_pid_in_group
    first_pid_m = group_id * GROUP_SIZE_M
    group_size_m = min(num_pid_m - first_pid_m, GROUP_SIZE_M)
    pid_m = first_pid_m + (pid % group_size_m)
    pid_n = (pid % num_pid_in_group) // group_size_m

    offs_am = (pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)) % M
    offs_bn = (pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)) % N
    offs_k = tl.arange(0, BLOCK_SIZE_K)
    a_ptrs = A + (offs_am[:, None] * stride_am + offs_k[None, :] * stride_ak)
    b_ptrs = B + (offs_k[:, None] * stride_bk + offs_bn[None, :] * stride_bn)

    As_ptrs = As + offs_am * stride_As_m
    offs_bsn = offs_bn // group_n
    Bs_ptrs = Bs + offs_bsn * stride_Bs_n

    accumulator = tl.zeros((BLOCK_SIZE_M, BLOCK_SIZE_N), dtype=tl.float32)
    for k in range(0, tl.cdiv(K, BLOCK_SIZE_K)):
        a = tl.load(a_ptrs, mask=offs_k[None, :] < K - k * BLOCK_SIZE_K, other=0.0)
        b = tl.load(b_ptrs, mask=offs_k[:, None] < K - k * BLOCK_SIZE_K, other=0.0)

        k_start = k * BLOCK_SIZE_K
        offs_ks = k_start // group_k
        a_s = tl.load(As_ptrs + offs_ks * stride_As_k)
        b_s = tl.load(Bs_ptrs + offs_ks * stride_Bs_k)

        accumulator += tl.dot(a, b) * a_s[:, None] * b_s[None, :]
        a_ptrs += BLOCK_SIZE_K * stride_ak
        b_ptrs += BLOCK_SIZE_K * stride_bk

    if C.dtype.element_ty == tl.bfloat16:
        c = accumulator.to(tl.bfloat16)
    elif C.dtype.element_ty == tl.float16:
        c = accumulator.to(tl.float16)
    else:
        c = accumulator.to(tl.float32)

    offs_cm = pid_m * BLOCK_SIZE_M + tl.arange(0, BLOCK_SIZE_M)
    offs_cn = pid_n * BLOCK_SIZE_N + tl.arange(0, BLOCK_SIZE_N)
    c_ptrs = C + stride_cm * offs_cm[:, None] + stride_cn * offs_cn[None, :]
    c_mask = (offs_cm[:, None] < M) & (offs_cn[None, :] < N)
    tl.store(c_ptrs, c, mask=c_mask)

def w8a8_triton_block_scaled_mm(
    A: torch.Tensor,
    B: torch.Tensor,
    As: torch.Tensor,
    Bs: torch.Tensor,
    block_size: list[int],
    output_dtype: torch.dtype = torch.float16,
) -> torch.Tensor:
    """This function performs matrix multiplication with block-wise
    quantization.
    It takes two input tensors `A` and `B` with scales `As` and `Bs`.
    The output is returned in the specified `output_dtype`.
    Args:
        A: The input tensor, e.g., activation.
        B: The input tensor, e.g., weight.
        As: The per-token-group quantization scale for `A`.
        Bs: The per-block quantization scale for `B`.
        block_size: The block size for per-block quantization. It should
        be 2-dim, e.g., [128, 128].
        output_dytpe: The dtype of the returned tensor.
    Returns:
        torch.Tensor: The result of matmul.
    """
    assert len(block_size) == 2
    block_n, block_k = block_size[0], block_size[1]

    assert A.shape[-1] == B.shape[-1]
    assert A.shape[:-1] == As.shape[:-1] and A.is_contiguous()
    assert triton.cdiv(A.shape[-1], block_k) == As.shape[-1]
    M = A.numel() // A.shape[-1]

    assert B.ndim == 2 and Bs.ndim == 2
    N, K = B.shape
    assert triton.cdiv(N, block_n) == Bs.shape[0]
    assert triton.cdiv(K, block_k) == Bs.shape[1]

    C_shape = A.shape[:-1] + (N,)
    C = A.new_empty(C_shape, dtype=output_dtype)

    configs = False # get_w8a8_block_fp8_configs(N, K, block_size[0], block_size[1])
    if configs:
        # Get the optimal config if there is one
        config = configs[min(configs.keys(), key=lambda x: abs(x - M))]
    else:
        # Default config
        # Block-wise quant: BLOCK_SIZE_N must be divisible by block_size[0]
        # BLOCK_SIZE_K must be divisible by block_size[1]
        config = {
            "BLOCK_SIZE_M": 64,
            "BLOCK_SIZE_N": block_size[0],
            "BLOCK_SIZE_K": block_size[1],
            "GROUP_SIZE_M": 32,
            "num_warps": 4,
            "num_stages": 2,
        }

    def grid(META):
        return (
            triton.cdiv(M, META["BLOCK_SIZE_M"]) * triton.cdiv(N, META["BLOCK_SIZE_N"]),
        )

    _w8a8_triton_block_scaled_mm[grid](
        A,
        B,
        C,
        As,
        Bs,
        M,
        N,
        K,
        block_n,
        block_k,
        A.stride(-2),
        A.stride(-1),
        B.stride(1),
        B.stride(0),
        C.stride(-2),
        C.stride(-1),
        As.stride(-2),
        As.stride(-1),
        Bs.stride(1),
        Bs.stride(0),
        **config,
    )

    return C

A = torch.randn(8096, 3072, device='xpu:0', dtype=torch.float16)
B = torch.randn(1024, 3072, device='xpu:0', dtype=torch.float16)
As = torch.randn(8096, 24, device='xpu:0', dtype=torch.float16)
Bs = torch.randn(8, 24, device='xpu:0', dtype=torch.float16)
block_size = [128, 128]
C = w8a8_triton_block_scaled_mm(A, B, As, Bs, block_size)
print(C)
```
I extracted `_w8a8_triton_block_scaled_mm` and `w8a8_triton_block_scaled_mm` directly from [fp8_utils.py](https://github.com/vllm-project/vllm/blob/808dd87b305426c809a21b2a6a4fb3ea607bca3f/vllm/model_executor/layers/quantization/utils/fp8_utils.py), only modifying [one line](https://github.com/vllm-project/vllm/blob/808dd87b305426c809a21b2a6a4fb3ea607bca3f/vllm/model_executor/layers/quantization/utils/fp8_utils.py#L1212C1-L1213C1) to avoid searching for a config and enforce that we use the default config.

Could you please confirm that this is the correct kernel, configurations, and parameters.

**Comment by quinnlp** [comment]
Converting A and B to fp8 also compiles and runs:
```python
...
A = torch.randn(8096, 3072, device='xpu:0', dtype=torch.float32)
A_fp8 = A.to(torch.float8_e4m3fn)
B = torch.randn(1024, 3072, device='xpu:0', dtype=torch.float32)
B_fp8 = B.to(torch.float8_e4m3fn)
As = torch.randn(8096, 24, device='xpu:0', dtype=torch.float32)
Bs = torch.randn(8, 24, device='xpu:0', dtype=torch.float32)
block_size = [128, 128]
C = w8a8_triton_block_scaled_mm(A_fp8, B_fp8, As, Bs, block_size)
print(C)
```

**Comment by montaguelhz** [comment]
> Converting A and B to fp8 also compiles and runs:
> 
> ...
> A = torch.randn(8096, 3072, device='xpu:0', dtype=torch.float32)
> A_fp8 = A.to(torch.float8_e4m3fn)
> B = torch.randn(1024, 3072, device='xpu:0', dtype=torch.float32)
> B_fp8 = B.to(torch.float8_e4m3fn)
> As = torch.randn(8096, 24, device='xpu:0', dtype=torch.float32)
> Bs = torch.randn(8, 24, device='xpu:0', dtype=torch.float32)
> block_size = [128, 128]
> C = w8a8_triton_block_scaled_mm(A_fp8, B_fp8, As, Bs, block_size)
> print(C)

Thank you so much for your help! The problem is that B.dtype is torch.float8_e4m3fn and A is quantified to torch.float8_e5m2 by default in xpu, which should be torch.float8_e4m3fn in cuda. Your insight is very important to me.
