### ISSUE TITLE
`tl.extra.intel.libdevice.round` causes ZE_RESULT_ERROR_INVALID_MODULE_UNLINKED on BMG (Xe2)

### ISSUE THREAD

**Issue by PatrykWo** [intel/intel-xpu-backend-for-triton#6659]
## Description

Triton kernels that use `tl.extra.intel.libdevice.round()` fail at runtime with **`ZE_RESULT_ERROR_INVALID_MODULE_UNLINKED`** on Intel Arc Pro B70 (BMG / Xe2 Battlemage). The SPIR-V module generated by the Triton compiler references an unresolved `libdevice.round` symbol that the Level Zero runtime cannot link.

This blocks two production kernels from vLLM:
- **`round_int8`** — JIT helper: `tl.extra.intel.libdevice.round(x).to(tl.int8)`
- **`_per_token_quant_int8`** — Per-token INT8 quantization kernel that calls `round_int8()` internally
- **`_per_token_group_quant_int8`** — Group variant, same call path

The same kernels work correctly on NVIDIA A6000 (CUDA backend uses `tl.extra.cuda.libdevice.round`).

## Minimal Reproducer

```python
import torch
import triton
import triton.language as tl

@triton.jit
def round_int8_repro(x):
    """Exact pattern from vLLM int8_utils.py (XPU branch)."""
    return tl.extra.intel.libdevice.round(x).to(tl.int8)

@triton.jit
def per_token_quant_repro(
    x_ptr, xq_ptr, scale_ptr,
    stride_x, stride_xq,
    N,
    BLOCK: tl.constexpr,
):
    row_id = tl.program_id(0)
    cols = tl.arange(0, BLOCK)
    mask = cols < N

    x = tl.load(x_ptr + row_id * stride_x + cols, mask=mask, other=0.0).to(tl.float32)
    absmax = tl.maximum(tl.max(tl.abs(x)), 1e-10)
    scale_x = absmax / 127
    x_q = x * (127 / absmax)
    x_q = round_int8_repro(x_q)  # <-- triggers INVALID_MODULE_UNLINKED

    tl.store(xq_ptr + row_id * stride_xq + cols, x_q, mask=mask)
    tl.store(scale_ptr + row_id, scale_x)


def test_libdevice_round():
    device = torch.device("xpu")
    M, N = 16, 128
    BLOCK = 128

    x = torch.randn(M, N, device=device, dtype=torch.float32)
    xq = torch.empty(M, N, device=device, dtype=torch.int8)
    scales = torch.empty(M, 1, device=device, dtype=torch.float32)

    per_token_quant_repro[(M,)](
        x, xq, scales, x.stride(0), xq.stride(0), N, BLOCK=BLOCK
    )
    torch.xpu.synchronize()
    print("Quantized:", xq[0, :8])
    print("Scales:", scales[:4, 0])

if __name__ == "__main__":
    test_libdevice_round()
```

**Expected**: INT8 quantized output.
**Actual**: `RuntimeError: ZE_RESULT_ERROR_INVALID_MODULE_UNLINKED` during module creation.

## Root Cause Analysis

`tl.extra.intel.libdevice.round` maps to a SPIR-V extended instruction. The Triton XPU backend generates a SPIR-V module that references this symbol, but the Level Zero runtime / IGC fails to resolve it at module creation time, returning `ZE_RESULT_ERROR_INVALID_MODULE_UNLINKED`.

Possible causes:
1. The libdevice `round` function is not being linked into the SPIR-V module
2. The BMG (Xe2) IGC compiler does not support this particular libdevice function
3. A missing or incorrect `OpExtInst` reference in the generated SPIR-V

## Affected vLLM Code

The XPU code path in [`vllm/model_executor/layers/quantization/utils/int8_utils.py`](https://github.com/vllm-project/vllm/blob/v0.19.0/vllm/model_executor/layers/quantization/utils/int8_utils.py#L95):

```python
elif current_platform.is_xpu():
    @triton.jit
    def round_int8(x):
        return tl.extra.intel.libdevice.round(x).to(tl.int8)
```

This is called by `_per_token_quant_int8`:
```python
@triton.jit
def _per_token_quant_int8(x_ptr, xq_ptr, scale_ptr, stride_x, stride_xq, N, BLOCK: tl.constexpr):
    ...
    x_q = round_int8(x_q)  # <-- fails here
    ...
```

## Environment

| Component | Version |
|-----------|---------|
| GPU | Intel Arc Pro B70 (BMG-G31, Xe2 Battlemage, PCI ID 0xe223) |
| PyTorch | 2.10.0+xpu |
| Triton | 3.6.0 (intel-xpu-backend-for-triton) |
| Level Zero | (bundled with PyTorch XPU wheel) |
| OS | Ubuntu 22.04 |

## Workaround

Not tested — a possible workaround avoiding `libdevice.round`:
```python
@triton.jit
def round_int8_workaround(x):
    # Banker's rounding via arithmetic (not using libdevice)
    return (x + 0.5).to(tl.int32).to(tl.int8)
```
This does not produce identical rounding behavior (truncation vs round-half-to-even) but may unblock users.

**Comment by PatrykWo** [comment]
## Triton Compilation Artifacts — `_per_token_quant_int8` kernel

Reproduced the `ZE_RESULT_ERROR_INVALID_MODULE_UNLINKED` error on **Intel Arc Pro B70** (BMG-G31, Xe2 Battlemage, PCI ID `0xe223`) using **XPU card 1** (`ZE_AFFINITY_MASK=1`).

### Environment
- **GPU**: Intel Arc Pro B70 (BMG-G31, 256 EUs, 32 GB)
- **PyTorch**: 2.10.0+xpu
- **Triton**: 3.6.0
- **vLLM**: 0.19.0
- **Docker**: `vllm-xpu-0.19.0` (built from `docker/Dockerfile.xpu`)
- **Level Zero**: v2, driver `1.14.36300+8`

### Reproduction
```bash
# Clean Triton cache, then run pytest
TRITON_CACHE_DIR=/workspace/triton-cache ZE_AFFINITY_MASK=1 \
  python -m pytest test_kernel_41_per_token_quant_int8_xpu.py -v -rs
```

**Result**: 10/10 tests skipped — `IGC compilation failed: ZE_RESULT_ERROR_INVALID_MODULE_UNLINKED` (after 23.23s)

### Root Cause (from compilation artifacts)

The kernel goes through the full Triton compilation pipeline (Source → TTIR → TTGIR → LLIR → SPIR-V) but **Level Zero fails to link the SPIR-V module**.

The smoking gun is in the **LLIR** (LLVM IR):
```llvm
declare spir_func float @__nv_roundf(float) local_unnamed_addr
  %43 = tail call spir_func float @__nv_roundf(float %39)
  %44 = tail call spir_func float @__nv_roundf(float %40)
  %45 = tail call spir_func float @__nv_roundf(float %41)
  %46 = tail call spir_func float @__nv_roundf(float %42)
```

The Triton source IR (`round_int8` function) uses:
```
tt.extern_elementwise %x {libname = "", libpath = "", pure = true, symbol = "__nv_roundf"}
```

This is an NVIDIA libdevice symbol. The Intel XPU backend links `/opt/venv/lib/python3.12/site-packages/triton/backends/intel/lib/libsycl-spir64-unknown-unknown.bc` as the `libdevice`, but the `__nv_roundf` symbol is **not resolved** by this library, resulting in the unlinked module error.

### Compilation Artifacts

Full Triton compilation artifacts (`.source`, `.ttir`, `.ttgir`, `.llir`, `.json`):
**Gist**: https://gist.github.com/PatrykWo/a3fd9310577108e6a37a28c616c71f2a

The SPIR-V binary (5KB) and full Triton cache tarball (48KB) are also available on request.

### Affected vLLM Kernels
- **#40**: `round_int8` — JIT helper called by `_per_token_quant_int8`
- **#41**: `_per_token_quant_int8` — the main per-token INT8 quantization kernel

Both are in `vllm/model_executor/layers/quantization/utils/int8_utils.py`.

**Comment by anmyachev** [comment]
Hi @PatrykWo, I checked on my side and it works correctly.

First of all, having `__nv_roundf` for XPU target is very strange - probably an issue with caching.

Could you run it again with the following command: `TRITON_ALWAYS_COMPILE=1 python [your repr.py]`?

**Comment by PatrykWo** [comment]
## Re-run with `TRITON_ALWAYS_COMPILE=1` — Same failure, but root cause is a **vLLM bug**, not Triton

@anmyachev, thanks for checking! I re-ran with `TRITON_ALWAYS_COMPILE=1` and a completely fresh `TRITON_CACHE_DIR`, and the failure persists:

```
TRITON_ALWAYS_COMPILE=1 TRITON_CACHE_DIR=/workspace/triton-cache ZE_AFFINITY_MASK=1 \
  python -m pytest test_kernel_41_per_token_quant_int8_xpu.py -v -rs
# 10/10 skipped — IGC compilation failed: ZE_RESULT_ERROR_INVALID_MODULE_UNLINKED (23.52s)
```

The freshly compiled LLIR still contains `__nv_roundf`:
```llvm
declare spir_func float @__nv_roundf(float) local_unnamed_addr
```

### Root cause found — vLLM v0.19.0 is missing the XPU branch

The Docker image ships **vLLM 0.19.0**, and in that version, `int8_utils.py` only has:

```python
if current_platform.is_rocm():
    @triton.jit
    def round_int8(x):
        return tl.extra.hip.libdevice.round(x).to(tl.int8)
else:
    @triton.jit
    def round_int8(x):
        return tl.extra.cuda.libdevice.round(x).to(tl.int8)  # ← XPU hits this!
```

The XPU platform falls through to the `else` branch and uses `tl.extra.cuda.libdevice.round`, which emits `__nv_roundf` — an NVIDIA symbol that Level Zero cannot link.

I confirmed `current_platform.is_xpu()` returns `True` in the container, so platform detection itself works. It's just the code path that's missing.

### Fix already merged in vLLM main

The fix was merged **one day after** v0.19.0:
- **PR**: [vllm-project/vllm#38825](https://github.com/vllm-project/vllm/pull/38825) — `[Intel][Triton] Support round_int8 for Intel backend`
- **Commit**: `bf8b022e6` (April 3, 2026)
- **v0.19.0 tag**: April 2, 2026

The fix adds the `elif current_platform.is_xpu():` branch with `tl.extra.intel.libdevice.round(x)`, which correctly maps to `__imf_roundf`.

### Conclusion

**This is a vLLM bug, not a Triton XPU backend issue.** You are right that `__nv_roundf` should not appear for an XPU target — and it doesn't when the correct Intel libdevice path is used. 

I'll close this issue since the fix is already upstream. We'll pick it up when we rebuild the Docker image for the next vLLM release. Sorry for the noise!

**Comment by PatrykWo** [comment]
Closing — root cause is a missing XPU code path in vLLM v0.19.0 (fixed in vllm-project/vllm#38825). Not a Triton XPU backend issue.
